# Generated by Django 4.2.7 on 2025-10-23 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^[0-9+\\-()\\s]{7,20}$')])),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(choices=[('Website', 'Website'), ('Referral', 'Referral'), ('Cold Call', 'Cold Call'), ('Social', 'Social Media'), ('Event', 'Event'), ('Other', 'Other')], max_length=50, verbose_name='Lead Source')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Med', 'Medium'), ('High', 'High')], default='Med', max_length=10)),
                ('owner', models.CharField(max_length=100, verbose_name='Assigned Owner')),
                ('use_case', models.TextField(help_text='What do they need?', verbose_name='Use Case')),
                ('next_action', models.CharField(blank=True, choices=[('Call', 'Call'), ('Email', 'Email'), ('Demo', 'Demo'), ('Meeting', 'Meeting'), ('None', 'None')], default='None', max_length=20, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('timeline', models.CharField(blank=True, max_length=100, null=True, verbose_name='Decision Timeline')),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
