# Generated by Django 5.2.7 on 2025-10-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_lead_created_by_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
