# Generated by Django 5.2.7 on 2025-10-31 07:11

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_leaverequest_applicant_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=myapp.models.document_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work Related'), ('contracts', 'Contracts'), ('certificates', 'Certificates'), ('other', 'Other')], default='personal', max_length=20)),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('team', 'Team Access'), ('public', 'Public')], default='private', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
