# Generated by Django 4.2.7 on 2025-10-31 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Client Name')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('project_name', models.CharField(max_length=300, verbose_name='Project Name')),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_duration', models.PositiveIntegerField(verbose_name='Duration')),
                ('duration_unit', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='months', max_length=10)),
                ('project_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Project Cost')),
                ('assigned_engineer', models.CharField(max_length=100, verbose_name='Assigned Engineer')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('on_hold', 'On Hold'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Onboarding',
                'verbose_name_plural': 'Client Onboardings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Client Name')),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('quote_number', models.CharField(max_length=50, unique=True, verbose_name='Quote #')),
                ('owner', models.CharField(max_length=100, verbose_name='Owner/Assignee')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Draft', max_length=20)),
                ('currency', models.CharField(choices=[('INR', 'INR (₹)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)')], default='INR', max_length=10)),
                ('valid_until', models.DateField(verbose_name='Valid Until')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes for client')),
                ('terms', models.TextField(blank=True, null=True, verbose_name='Terms & Conditions')),
                ('project_pdf', models.FileField(blank=True, null=True, upload_to='quotes/pdfs/', verbose_name='Project Details PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Item Description')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='GST %')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.quote')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
