# Generated by Django 4.2.7 on 2025-11-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_quote_items_delete_quoteitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientOnboarding',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
