# Generated by Django 4.2.7 on 2025-11-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_create_quote_clientonboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('emp_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Employee Code')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('address_current', models.TextField(blank=True, null=True, verbose_name='Current Address')),
                ('address_permanent', models.TextField(blank=True, null=True, verbose_name='Permanent Address')),
                ('designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department')),
                ('manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reporting Manager')),
                ('employment_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Intern', 'Intern')], max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('probation', models.IntegerField(blank=True, null=True, verbose_name='Probation (months)')),
                ('ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='CTC (Annual)')),
                ('basic', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='HRA')),
                ('allowances', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deductions', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Variable/Bonus')),
                ('pay_cycle', models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Bi-weekly', 'Bi-weekly')], max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=20, null=True, verbose_name='IFSC')),
                ('upi', models.CharField(blank=True, max_length=100, null=True, verbose_name='UPI ID')),
                ('pan', models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN')),
                ('aadhaar', models.CharField(blank=True, max_length=20, null=True, verbose_name='Aadhaar')),
                ('uan', models.CharField(blank=True, max_length=50, null=True, verbose_name='UAN (PF)')),
                ('esic', models.CharField(blank=True, max_length=50, null=True, verbose_name='ESIC No')),
                ('gst', models.CharField(blank=True, max_length=50, null=True, verbose_name='GST (if any)')),
                ('emg_name1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Primary Contact Name')),
                ('emg_relation1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Primary Relation')),
                ('emg_phone1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Primary Phone')),
                ('emg_name2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Secondary Contact Name')),
                ('emg_relation2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Secondary Relation')),
                ('emg_phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary Phone')),
                ('asset_laptop', models.CharField(blank=True, max_length=200, null=True)),
                ('asset_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('asset_other', models.CharField(blank=True, max_length=200, null=True)),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Work Email')),
                ('github', models.CharField(blank=True, max_length=200, null=True, verbose_name='Git/GitHub')),
                ('pm_tool', models.CharField(blank=True, max_length=200, null=True, verbose_name='Jira/PM Tool')),
                ('vpn', models.CharField(blank=True, max_length=10, null=True, verbose_name='VPN Access')),
                ('access_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='Access Level')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
    ]
