# Generated by Django 4.2.7 on 2025-11-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='annual_leave',
            field=models.IntegerField(default=20, verbose_name='Annual Leave Days'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_leave',
            field=models.IntegerField(default=3, verbose_name='Emergency Leave Days'),
        ),
        migrations.AddField(
            model_name='employee',
            name='maternity_leave',
            field=models.IntegerField(default=90, verbose_name='Maternity Leave Days'),
        ),
        migrations.AddField(
            model_name='employee',
            name='paternity_leave',
            field=models.IntegerField(default=15, verbose_name='Paternity Leave Days'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_leave',
            field=models.IntegerField(default=5, verbose_name='Personal Leave Days'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_leave',
            field=models.IntegerField(default=12, verbose_name='Sick Leave Days'),
        ),
    ]
