# Generated by Django 5.2.7 on 2025-11-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_employee_annual_leave_employee_emergency_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='doc_aadhaar',
            field=models.FileField(blank=True, null=True, upload_to='uploads/employees/documents/', verbose_name='Aadhaar Card'),
        ),
        migrations.AddField(
            model_name='employee',
            name='doc_bank',
            field=models.FileField(blank=True, null=True, upload_to='uploads/employees/documents/', verbose_name='Bank Passbook/Cancelled Cheque'),
        ),
        migrations.AddField(
            model_name='employee',
            name='doc_current_offer',
            field=models.FileField(blank=True, null=True, upload_to='uploads/employees/documents/', verbose_name='Current Company Offer/Appointment Letter'),
        ),
        migrations.AddField(
            model_name='employee',
            name='doc_education',
            field=models.FileField(blank=True, null=True, upload_to='uploads/employees/documents/', verbose_name='Education Certificates'),
        ),
        migrations.AddField(
            model_name='employee',
            name='doc_experience',
            field=models.FileField(blank=True, null=True, upload_to='uploads/employees/documents/', verbose_name='Experience Letter(s)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='doc_pan',
            field=models.FileField(blank=True, null=True, upload_to='uploads/employees/documents/', verbose_name='PAN Card'),
        ),
        migrations.AddField(
            model_name='employee',
            name='doc_prev_offer_relieve',
            field=models.FileField(blank=True, null=True, upload_to='uploads/employees/documents/', verbose_name='Previous Company Offer/Relieving Letter'),
        ),
        migrations.AddField(
            model_name='employee',
            name='doc_salary_slips',
            field=models.FileField(blank=True, null=True, upload_to='uploads/employees/documents/', verbose_name='Latest Month Salary Slips'),
        ),
    ]
