# Generated by Django 4.2.7 on 2025-11-04 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0013_employee_doc_aadhaar_employee_doc_bank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_id', models.CharField(max_length=100, verbose_name='Receiver ID')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='Receiver Name')),
                ('sender_name', models.CharField(max_length=200, verbose_name='Sender Name')),
                ('sender_designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sender Designation')),
                ('sender_department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sender Department')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender User')),
            ],
            options={
                'verbose_name': 'Employee Message',
                'verbose_name_plural': 'Employee Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
