# Generated by Django 4.2.7 on 2025-11-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_employeemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='messages/attachments/%Y/%m/%d/', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='employeemessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Attachment Name'),
        ),
        migrations.AddField(
            model_name='employeemessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/images/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='employeemessage',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
    ]
