# Generated by Django 4.2.7 on 2025-11-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_employeemessage_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Admin', 'Admin')], default='Employee', max_length=20, null=True, verbose_name='Role'),
        ),
    ]
