# Generated by Django 4.2.7 on 2025-11-06 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0016_employee_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'date')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='myapp.employee', verbose_name='Employee'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'date'), ('employee', 'date')},
        ),
    ]
