# Generated by Django 4.2.7 on 2025-11-10 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0017_alter_attendance_unique_together_attendance_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Payment Amount')),
                ('basic', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Basic Salary')),
                ('hra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='HRA')),
                ('allowances', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Allowances')),
                ('deductions', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Deductions')),
                ('variable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Variable/Bonus')),
                ('ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='CTC')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank_transfer', max_length=20, verbose_name='Payment Method')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20, verbose_name='Status')),
                ('payment_month', models.IntegerField(verbose_name='Payment Month (1-12)')),
                ('payment_year', models.IntegerField(verbose_name='Payment Year')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='myapp.employee', verbose_name='Employee')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['employee', '-payment_date'], name='myapp_payme_employe_75f311_idx'), models.Index(fields=['payment_year', 'payment_month'], name='myapp_payme_payment_3d27af_idx')],
            },
        ),
    ]
