# Generated by Django 5.2.7 on 2025-11-13 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_employee_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookkeepingChecklistRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('prepared_by', models.CharField(max_length=255)),
                ('cash_book_updated', models.BooleanField(default=False)),
                ('bank_entries_reconciled', models.BooleanField(default=False)),
                ('inventory_updated', models.BooleanField(default=False)),
                ('outstanding_notes', models.TextField(blank=True, null=True)),
                ('reconciliation_documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookkeeping_checklists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookkeeping Checklist Record',
                'verbose_name_plural': 'Bookkeeping Checklist Records',
                'ordering': ['-closing_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GSTFilingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(max_length=15, verbose_name='GSTIN')),
                ('return_period', models.CharField(help_text='YYYY-MM format', max_length=7)),
                ('return_type', models.CharField(max_length=20)),
                ('filing_scheme', models.CharField(max_length=30)),
                ('tax_payable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('input_credit_utilized', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('internal_remarks', models.TextField(blank=True, null=True)),
                ('data_files', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_filing_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GST Filing Record',
                'verbose_name_plural': 'GST Filing Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ITRFilingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxpayer_name', models.CharField(max_length=255)),
                ('pan', models.CharField(max_length=10)),
                ('assessment_year', models.CharField(max_length=9)),
                ('return_form', models.CharField(max_length=10)),
                ('client_category', models.CharField(max_length=50)),
                ('books_of_account', models.CharField(max_length=50)),
                ('computation_notes', models.TextField(blank=True, null=True)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itr_filing_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ITR Filing Record',
                'verbose_name_plural': 'ITR Filing Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ROCComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('cin_llpin', models.CharField(max_length=25, verbose_name='CIN / LLPIN')),
                ('financial_year', models.CharField(max_length=20)),
                ('agm_date', models.DateField(blank=True, null=True)),
                ('compliance_period', models.CharField(max_length=100)),
                ('digital_signature', models.CharField(max_length=100)),
                ('pending_queries', models.TextField(blank=True, null=True)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roc_compliance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ROC Compliance Record',
                'verbose_name_plural': 'ROC Compliance Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TDSComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deductor_tan', models.CharField(max_length=10, verbose_name='Deductor TAN')),
                ('section', models.CharField(max_length=30)),
                ('deduction_month', models.CharField(help_text='YYYY-MM format', max_length=7)),
                ('total_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tds_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('challan_number', models.CharField(max_length=25)),
                ('challan_date', models.DateField(blank=True, null=True)),
                ('proofs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_compliance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TDS Compliance Record',
                'verbose_name_plural': 'TDS Compliance Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
