# Generated by Django 4.2.7 on 2025-11-14 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0021_bookkeepingchecklistrecord_gstfilingrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupIndiaRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity_name', models.CharField(max_length=255, verbose_name='Legal Entity Name')),
                ('incorporation_date', models.DateField(blank=True, null=True, verbose_name='Incorporation Date')),
                ('entity_type', models.CharField(choices=[('Pvt Ltd', 'Pvt Ltd'), ('LLP', 'LLP'), ('Partnership', 'Partnership'), ('OPC', 'OPC'), ('Section 8', 'Section 8')], max_length=50, verbose_name='Entity Type')),
                ('industry_sector', models.CharField(choices=[('Tech', 'Tech'), ('Manufacturing', 'Manufacturing'), ('Fintech', 'Fintech'), ('Healthcare', 'Healthcare'), ('Other', 'Other')], max_length=50, verbose_name='Industry Sector')),
                ('authorised_contact', models.CharField(blank=True, max_length=255, verbose_name='Authorised Contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('innovation_usp', models.TextField(blank=True, verbose_name='Innovation / USP')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startup_india_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Start-up India Registration',
                'verbose_name_plural': 'Start-up India Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
