# Generated by Django 4.2.7 on 2025-11-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_startupindiaregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupindiaregistration',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
