# Generated by Django 4.2.7 on 2025-11-14 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0023_alter_startupindiaregistration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSSAILicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_brand_name', models.CharField(max_length=255, verbose_name='Business / Brand Name')),
                ('licence_type', models.CharField(choices=[('Basic', 'Basic'), ('State', 'State'), ('Central', 'Central'), ('Import/Export', 'Import/Export')], max_length=50, verbose_name='Licence Type')),
                ('business_nature', models.CharField(choices=[('Manufacturing', 'Manufacturing'), ('Distributor', 'Distributor'), ('Storage', 'Storage'), ('Catering', 'Catering')], max_length=50, verbose_name='Business Nature')),
                ('premises_address', models.TextField(blank=True, verbose_name='Premises Address')),
                ('employees', models.IntegerField(blank=True, null=True, verbose_name='Employees')),
                ('licence_tenure', models.CharField(choices=[('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('5 Years', '5 Years')], max_length=20, verbose_name='Licence Tenure')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fssai_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FSSAI License',
                'verbose_name_plural': 'FSSAI Licenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
