# Generated by Django 5.2.7 on 2025-11-14 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_fssailicense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MSMEUdyamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255, verbose_name='Entity Name')),
                ('organisation_type', models.CharField(choices=[('Proprietorship', 'Proprietorship'), ('Partnership', 'Partnership'), ('LLP', 'LLP'), ('Company', 'Company')], max_length=50, verbose_name='Organisation Type')),
                ('plant_machinery_investment', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Plant & Machinery Investment (₹)')),
                ('annual_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Annual Turnover (₹)')),
                ('principal_activity', models.TextField(blank=True, verbose_name='Principal Activity')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msme_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MSME / Udyam Registration',
                'verbose_name_plural': 'MSME / Udyam Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
