# Generated by Django 5.2.7 on 2025-11-14 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_msmeudyamregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLLPRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('Pvt Ltd', 'Pvt Ltd'), ('LLP', 'LLP'), ('OPC', 'OPC'), ('Section 8', 'Section 8')], max_length=50, verbose_name='Entity Type')),
                ('directors_partners', models.PositiveIntegerField(default=1, verbose_name='Directors / Partners')),
                ('proposed_names', models.TextField(verbose_name='Proposed Names (3)')),
                ('authorised_capital', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Authorised Capital (₹)')),
                ('registered_office', models.TextField(verbose_name='Registered Office')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_llp_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company / LLP Registration',
                'verbose_name_plural': 'Company / LLP Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
