# Generated by Django 5.2.7 on 2025-11-14 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_companyllpregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirePollutionLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_type', models.CharField(choices=[('Manufacturing', 'Manufacturing'), ('Warehouse', 'Warehouse'), ('Restaurant', 'Restaurant'), ('Retail', 'Retail'), ('Office', 'Office')], max_length=50, verbose_name='Establishment Type')),
                ('built_up_area', models.PositiveIntegerField(verbose_name='Built-up Area (sq.ft)')),
                ('pollution_category', models.CharField(choices=[('White', 'White'), ('Green', 'Green'), ('Orange', 'Orange'), ('Red', 'Red')], max_length=20, verbose_name='Pollution Category')),
                ('safety_installations', models.TextField(verbose_name='Safety Installations')),
                ('documents', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fire_pollution_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fire & Pollution License',
                'verbose_name_plural': 'Fire & Pollution Licenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
