# Generated by Django 5.2.7 on 2025-11-14 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_firepollutionlicense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ISOCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('ISO 9001', 'ISO 9001'), ('ISO 14001', 'ISO 14001'), ('ISO 45001', 'ISO 45001'), ('ISO 27001', 'ISO 27001')], max_length=50, verbose_name='Standard')),
                ('locations', models.PositiveIntegerField(default=1, help_text='No. of sites', verbose_name='Locations')),
                ('employee_strength', models.PositiveIntegerField(blank=True, null=True, verbose_name='Employee Strength')),
                ('existing_certifications', models.TextField(blank=True, verbose_name='Existing Certifications')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iso_certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ISO Certification',
                'verbose_name_plural': 'ISO Certifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
