# Generated by Django 4.2.7 on 2025-11-15 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0028_isocertification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrademarkFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_logo', models.TextField(help_text='Describe or attach logo', verbose_name='Brand / Logo')),
                ('applicant_type', models.CharField(choices=[('Individual', 'Individual'), ('Firm', 'Firm'), ('Company/LLP', 'Company/LLP'), ('Trust/Society', 'Trust/Society')], max_length=50, verbose_name='Applicant Type')),
                ('classes', models.CharField(help_text='e.g. 35, 42', max_length=200, verbose_name='Classes')),
                ('first_use_date', models.DateField(blank=True, null=True, verbose_name='First Use Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trademark_filings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trademark Filing',
                'verbose_name_plural': 'Trademark Filings',
                'ordering': ['-created_at'],
            },
        ),
    ]
