# Generated by Django 4.2.7 on 2025-11-15 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0029_trademarkfiling'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrademarkFilingCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existing_tm_numbers', models.TextField(blank=True, help_text='If any', verbose_name='Existing TM Numbers')),
                ('portfolio_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Portfolio Size')),
                ('watch_scope', models.CharField(blank=True, choices=[('Identical', 'Identical'), ('Similar', 'Similar'), ('Domains/Handles', 'Domains/Handles')], max_length=50, verbose_name='Watch Scope')),
                ('renewal_month', models.CharField(blank=True, help_text='e.g. January, February', max_length=50, verbose_name='Renewal Month')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trademark_filing_compliances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trademark Filing + Compliance',
                'verbose_name_plural': 'Trademark Filing + Compliances',
                'ordering': ['-created_at'],
            },
        ),
    ]
