# Generated by Django 4.2.7 on 2025-11-15 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0030_trademarkfilingcompliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrademarkFilingInstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency_reason', models.TextField(help_text='Launch / diligence / other', verbose_name='Urgency Reason')),
                ('filing_window', models.CharField(blank=True, choices=[('Before 1 PM', 'Before 1 PM'), ('Before 6 PM', 'Before 6 PM'), ('Weekend', 'Weekend')], max_length=50, verbose_name='Filing Window')),
                ('contact_mobile', models.CharField(blank=True, help_text='+91XXXXXXXXXX', max_length=20, verbose_name='Contact Mobile')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trademark_filing_instants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trademark Filing (Instant Process)',
                'verbose_name_plural': 'Trademark Filing (Instant Process)',
                'ordering': ['-created_at'],
            },
        ),
    ]
