# Generated by Django 4.2.7 on 2025-11-15 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0031_trademarkfilinginstant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddressChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('Company', 'Company'), ('LLP', 'LLP')], max_length=50, verbose_name='Entity Type')),
                ('shift_type', models.CharField(choices=[('Within city', 'Within city'), ('Within ROC', 'Within ROC'), ('Inter-ROC / State', 'Inter-ROC / State')], max_length=50, verbose_name='Type of Shift')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Effective Date')),
                ('new_address', models.TextField(help_text='Complete address', verbose_name='New Address')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_address_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Address Change',
                'verbose_name_plural': 'Company Address Changes',
                'ordering': ['-created_at'],
            },
        ),
    ]
