# Generated by Django 4.2.7 on 2025-11-15 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0032_companyaddresschange'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOAAlteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alteration_type', models.CharField(choices=[('Object change', 'Object change'), ('Name change', 'Name change'), ('Authorised capital', 'Authorised capital')], max_length=50, verbose_name='Alteration Type')),
                ('proposed_object_name', models.TextField(help_text='Draft text / options', verbose_name='Proposed Object/Name')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Effective Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moa_alterations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MOA Alteration',
                'verbose_name_plural': 'MOA Alterations',
                'ordering': ['-created_at'],
            },
        ),
    ]
