# Generated by Django 5.2.7 on 2025-11-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_moaalteration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Client Name')),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Invoice #')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('owner', models.CharField(max_length=100, verbose_name='Owner/Assignee')),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Partial', 'Partial'), ('Cancelled', 'Cancelled')], default='Unpaid', max_length=20)),
                ('currency', models.CharField(choices=[('INR', 'INR (₹)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)')], default='INR', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='GST Percentage (%)')),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='GST Amount')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('terms', models.TextField(blank=True, null=True, verbose_name='Terms & Conditions')),
                ('items', models.JSONField(blank=True, default=list, help_text='List of invoice items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
    ]
