# Generated by Django 4.2.7 on 2025-11-18 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_invoice'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS myapp_invoicepayment;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
