# Generated by Django 4.2.7 on 2025-11-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_delete_invoicepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount Received'),
        ),
    ]
