# Generated by Django 4.2.7 on 2025-11-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_invoice_payment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeepingchecklistrecord',
            name='lead_source',
            field=models.CharField(default='website', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='companyaddresschange',
            name='lead_source',
            field=models.CharField(default='website', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='companyllpregistration',
            name='lead_source',
            field=models.CharField(default='website', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='firepollutionlicense',
            name='lead_source',
            field=models.CharField(default='website', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='fssailicense',
            name='lead_source',
            field=models.CharField(default='website', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='gstfilingrecord',
            name='lead_source',
            field=models.CharField(default='website', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='isocertification',
            name='lead_source',
            field=models.CharField(default='website', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='itrfilingrecord',
            name='lead_source',
            field=models.CharField(default='website', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='moaalteration',
            name='lead_source',
            field=models.CharField(default='website', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='msmeudyamregistration',
            name='lead_source',
            field=models.CharField(default='website', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='roccompliancerecord',
            name='lead_source',
            field=models.CharField(default='website', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='startupindiaregistration',
            name='lead_source',
            field=models.CharField(default='website', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='tdscompliancerecord',
            name='lead_source',
            field=models.CharField(default='website', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='trademarkfiling',
            name='lead_source',
            field=models.CharField(default='website', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='trademarkfilingcompliance',
            name='lead_source',
            field=models.CharField(default='website', max_length=100, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='trademarkfilinginstant',
            name='lead_source',
            field=models.CharField(default='website', max_length=100, verbose_name='Lead Source'),
        ),
    ]
