# Generated by Django 4.2.7 on 2025-11-19 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_bookkeepingchecklistrecord_lead_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeepingchecklistrecord',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookkeeping_records', to='myapp.employee', verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='companyaddresschange',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_address_change_records', to='myapp.employee', verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='companyllpregistration',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_company_llp_records', to='myapp.employee', verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='firepollutionlicense',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fire_pollution_records', to='myapp.employee', verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='fssailicense',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fssai_records', to='myapp.employee', verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='gstfilingrecord',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gst_records', to='myapp.employee', verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='isocertification',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_iso_records', to='myapp.employee', verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='itrfilingrecord',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_itr_records', to='myapp.employee', verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='moaalteration',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_moa_alteration_records', to='myapp.employee', verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='msmeudyamregistration',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_msme_records', to='myapp.employee', verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='roccompliancerecord',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roc_records', to='myapp.employee', verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='startupindiaregistration',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_startup_records', to='myapp.employee', verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='tdscompliancerecord',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tds_records', to='myapp.employee', verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='trademarkfiling',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trademark_records', to='myapp.employee', verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='trademarkfilingcompliance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trademark_compliance_records', to='myapp.employee', verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='trademarkfilinginstant',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trademark_instant_records', to='myapp.employee', verbose_name='Assigned To'),
        ),
    ]
