# Generated by Django 4.2.7 on 2025-11-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_bookkeepingchecklistrecord_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeepingchecklistrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('submitted', 'Submitted'), ('complete', 'Complete')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='gstfilingrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('submitted', 'Submitted'), ('complete', 'Complete')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='itrfilingrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('submitted', 'Submitted'), ('complete', 'Complete')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='roccompliancerecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('submitted', 'Submitted'), ('complete', 'Complete')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='tdscompliancerecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('submitted', 'Submitted'), ('complete', 'Complete')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
