# Generated by Django 5.2.7 on 2025-11-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_roccompliancerecord_applicant_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstfilingrecord',
            name='applicant_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='gstfilingrecord',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='gstfilingrecord',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Applicant Name'),
        ),
        migrations.AddField(
            model_name='gstfilingrecord',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='gstfilingrecord',
            name='applicant_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number'),
        ),
    ]
