# Generated by Django 5.2.7 on 2025-11-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_startupindiaregistration_applicant_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaddresschange',
            name='applicant_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='companyaddresschange',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='companyaddresschange',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Applicant Name'),
        ),
        migrations.AddField(
            model_name='companyaddresschange',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='companyaddresschange',
            name='applicant_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number'),
        ),
        migrations.AddField(
            model_name='companyllpregistration',
            name='applicant_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='companyllpregistration',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='companyllpregistration',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Applicant Name'),
        ),
        migrations.AddField(
            model_name='companyllpregistration',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='companyllpregistration',
            name='applicant_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number'),
        ),
        migrations.AddField(
            model_name='firepollutionlicense',
            name='applicant_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='firepollutionlicense',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='firepollutionlicense',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Applicant Name'),
        ),
        migrations.AddField(
            model_name='firepollutionlicense',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='firepollutionlicense',
            name='applicant_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number'),
        ),
        migrations.AddField(
            model_name='fssailicense',
            name='applicant_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='fssailicense',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='fssailicense',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Applicant Name'),
        ),
        migrations.AddField(
            model_name='fssailicense',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='fssailicense',
            name='applicant_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number'),
        ),
        migrations.AddField(
            model_name='isocertification',
            name='applicant_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='isocertification',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='isocertification',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Applicant Name'),
        ),
        migrations.AddField(
            model_name='isocertification',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='isocertification',
            name='applicant_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number'),
        ),
        migrations.AddField(
            model_name='moaalteration',
            name='applicant_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='moaalteration',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='moaalteration',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Applicant Name'),
        ),
        migrations.AddField(
            model_name='moaalteration',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='moaalteration',
            name='applicant_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number'),
        ),
        migrations.AddField(
            model_name='msmeudyamregistration',
            name='applicant_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='msmeudyamregistration',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='msmeudyamregistration',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Applicant Name'),
        ),
        migrations.AddField(
            model_name='msmeudyamregistration',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='msmeudyamregistration',
            name='applicant_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number'),
        ),
        migrations.AddField(
            model_name='trademarkfiling',
            name='applicant_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='trademarkfiling',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='trademarkfiling',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Applicant Name'),
        ),
        migrations.AddField(
            model_name='trademarkfiling',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='trademarkfiling',
            name='applicant_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number'),
        ),
        migrations.AddField(
            model_name='trademarkfilingcompliance',
            name='applicant_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='trademarkfilingcompliance',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='trademarkfilingcompliance',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Applicant Name'),
        ),
        migrations.AddField(
            model_name='trademarkfilingcompliance',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='trademarkfilingcompliance',
            name='applicant_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number'),
        ),
        migrations.AddField(
            model_name='trademarkfilinginstant',
            name='applicant_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='trademarkfilinginstant',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='trademarkfilinginstant',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Applicant Name'),
        ),
        migrations.AddField(
            model_name='trademarkfilinginstant',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='trademarkfilinginstant',
            name='applicant_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number'),
        ),
    ]
