# Generated by Django 4.2.7 on 2025-11-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_companyaddresschange_applicant_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed password. If set, user must login with password instead of phone.', max_length=128, null=True, verbose_name='Password'),
        ),
    ]
