# Generated by Django 4.2.7 on 2025-11-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_add_password_to_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255, verbose_name='Account Name')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank Name')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('ifsc', models.CharField(max_length=20, verbose_name='IFSC Code')),
                ('branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Account')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Bank Account',
                'verbose_name_plural': 'Company Bank Accounts',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='selected_bank_accounts',
            field=models.JSONField(blank=True, default=list, help_text='List of selected bank account IDs to display on invoice'),
        ),
    ]
