# Generated by Django 4.2.7 on 2025-12-01 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_add_address_and_amount_to_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='myapp.employee', verbose_name='Assigned To Employee'),
        ),
    ]
