# Generated by Django 4.2.7 on 2025-12-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_add_assigned_to_employee_to_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='conversion_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Won', 'Won'), ('Lost', 'Lost')], default='Pending', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
