from django.urls import path
from .import views 

urlpatterns =[
  path('', views.home, name='home'),
  path('login/',views.login_view,name='login'),
  path('about/',views.about,name='about'),
  path('services/',views.services,name='services'),
  path('projects/',views.projects,name='projects'),
  path('careers/',views.careers,name='careers'),
  path('contact/',views.contact,name='contact'),
  path('quote/',views.quote,name='quote'),
  path('dashboard/',views.dashboard,name='dashboard'),
  path('dashboard/accounts-department/', views.accounts_department, name='accounts_department'),
  path('dashboard/backoffice-department/', views.backoffice_department, name='backoffice_department'),
  path('dashboard/service-forms/', views.service_forms, name='service_forms'),
  path('dashboard/service-leads/', views.service_leads, name='service_leads'),
  path('dashboard/service-leads/assign/', views.assign_service_lead, name='assign_service_lead'),
  path('dashboard/service-leads/delete/', views.delete_service_lead, name='delete_service_lead'),
  path('dashboard/service-leads/update-status/', views.update_service_lead_status, name='update_service_lead_status'),
  path('leads/',views.leads,name='leads'),
  path('leads/<int:lead_id>/',views.lead_detail,name='lead_detail'),
  path('leads/<int:lead_id>/edit/',views.lead_edit,name='lead_edit'),
  path('leads/<int:lead_id>/delete/',views.lead_delete,name='lead_delete'),
  path('leads/<int:lead_id>/get-data/',views.lead_get_data,name='lead_get_data'),
  path('leads/filter/',views.lead_filter,name='lead_filter'),
  path('leads/export/',views.lead_export,name='lead_export'),
  path('leads/import/',views.lead_import,name='lead_import'),
  path('leads/import-export/',views.leads_import_export,name='leads_import_export'),
  path('accounts/',views.accounts,name='accounts'),
  path('accounts/pay-employee/<int:employee_id>/',views.pay_employee,name='pay_employee'),
  path('contacts/',views.contacts,name='contacts'),
  path('invoices/',views.invoices,name='invoices'),
  path('invoices/<str:invoice_type>/<int:invoice_id>/download/',views.invoice_pdf_download,name='invoice_pdf_download'),
  path('invoices/download/table/', views.invoice_table_pdf_download, name='invoice_table_pdf_download'),
  path('invoices/<int:invoice_id>/view/', views.invoice_detail, name='invoice_detail'),
  path('invoices/<str:invoice_type>/<int:invoice_id>/edit/',views.invoice_edit,name='invoice_edit'),
  path('invoices/<str:invoice_type>/<int:invoice_id>/delete/',views.invoice_delete,name='invoice_delete'),
  path('invoices/<int:invoice_id>/pay-due/', views.invoice_pay_due, name='invoice_pay_due'),
  path('quotes/',views.quotes,name='quotes'),
  path('clients/',views.clients,name='clients'),
  path('clients/update-lead-onboard-status/',views.update_lead_onboard_status,name='update_lead_onboard_status'),
  path('clients/get-employees-by-department/',views.get_employees_by_department,name='get_employees_by_department'),
  path('clients/get-project-details/<int:client_id>/',views.get_project_details,name='get_project_details'),
  path('employees/',views.employees,name='employees'),
  path('employees/<int:employee_id>/view/',views.employee_view,name='employee_view'),
  path('employees/<int:employee_id>/delete/',views.employee_delete,name='employee_delete'),
  path('attendance/',views.attendance,name='attendance'),
  path('attendance/data/',views.attendance_data_api,name='attendance_data_api'),
  path('in-out/',views.in_out,name='in_out'),
  path('leave/',views.leave,name='leave'),
  path('dashboard/leaves/',views.dashboard_leaves,name='dashboard_leaves'),
  path('dashboard/leaves/<int:leave_id>/update-status/',views.leave_status_update,name='leave_status_update'),
  path('dashboard/messages/',views.admin_messages,name='admin_messages'),
  path('reports/',views.reports,name='reports'),
  path('settings/',views.settings_view,name='settings'),
  path('settings/change-password/',views.change_password_view,name='change_password'),
  path('bank-accounts/',views.bank_accounts_list,name='bank_accounts_list'),
  path('bank-accounts/create/',views.bank_account_create,name='bank_account_create'),
  path('bank-accounts/<int:account_id>/update/',views.bank_account_update,name='bank_account_update'),
  path('bank-accounts/<int:account_id>/toggle-status/',views.bank_account_toggle_status,name='bank_account_toggle_status'),
  path('bank-accounts/<int:account_id>/delete/',views.bank_account_delete,name='bank_account_delete'),
  path('logout/',views.logout_view,name='logout'),
  path('project-management/',views.project_management,name='project_management'),
  path('project-management/<int:onboard_id>/view/',views.project_onboard_view,name='project_onboard_view'),
  path('project-management/<int:onboard_id>/update/',views.project_onboard_update,name='project_onboard_update'),
  
  # Employee Portal URLs
  path('employee/',views.employee_dashboard,name='employee_dashboard'),
  path('employee/dashboard/',views.employee_dashboard,name='employee_dashboard'),
  path('employee/projects/',views.employee_projects,name='employee_projects'),
  path('employee/projects/new/',views.employee_new_project,name='employee_new_project'),
  path('employee/projects/<int:project_id>/',views.employee_project_detail,name='employee_project_detail'),
  path('employee/projects/<int:project_id>/update-status/',views.employee_update_project_status,name='employee_update_project_status'),
  path('employee/projects/<int:project_id>/start/',views.employee_start_project,name='employee_start_project'),
  path('employee/projects/<int:project_id>/continue/',views.employee_continue_project,name='employee_continue_project'),
  path('employee/projects/<int:project_id>/finish/',views.employee_finish_project,name='employee_finish_project'),
  path('employee/accounts/',views.employee_accounts,name='employee_accounts'),
  path('employee/accounts/<str:section>/<int:pk>/edit/',views.employee_accounts_edit,name='employee_accounts_edit'),
  path('employee/accounts/<str:section>/<int:pk>/delete/',views.employee_accounts_delete,name='employee_accounts_delete'),
  path('employee/backoffice/',views.employee_backoffice,name='employee_backoffice'),
  path('employee/backoffice/startup/<int:record_id>/update-status/',views.update_startup_status,name='update_startup_status'),
  path('employee/backoffice/fssai/<int:record_id>/update-status/',views.update_fssai_status,name='update_fssai_status'),
  path('employee/backoffice/msme/<int:record_id>/update-status/',views.update_msme_status,name='update_msme_status'),
  path('employee/backoffice/company-llp/<int:record_id>/update-status/',views.update_company_llp_status,name='update_company_llp_status'),
  path('employee/backoffice/fire-pollution/<int:record_id>/update-status/',views.update_fire_pollution_status,name='update_fire_pollution_status'),
  path('employee/backoffice/iso/<int:record_id>/update-status/',views.update_iso_status,name='update_iso_status'),
  path('employee/backoffice/trademark/<int:record_id>/update-status/',views.update_trademark_status,name='update_trademark_status'),
  path('employee/backoffice/trademark-compliance/<int:record_id>/update-status/',views.update_trademark_compliance_status,name='update_trademark_compliance_status'),
  path('employee/backoffice/trademark-instant/<int:record_id>/update-status/',views.update_trademark_instant_status,name='update_trademark_instant_status'),
  path('employee/backoffice/address-change/<int:record_id>/update-status/',views.update_address_change_status,name='update_address_change_status'),
  path('employee/backoffice/moa-alteration/<int:record_id>/update-status/',views.update_moa_alteration_status,name='update_moa_alteration_status'),
  path('employee/backoffice/din-application/<int:record_id>/update-status/',views.update_din_application_status,name='update_din_application_status'),
  path('employee/backoffice/gst-registration/<int:record_id>/update-status/',views.update_gst_registration_status,name='update_gst_registration_status'),
  path('employee/backoffice/gst-filing/<int:record_id>/update-status/',views.update_gst_filing_status,name='update_gst_filing_status'),
  path('employee/backoffice/company-compliance-roc-llp/<int:record_id>/update-status/',views.update_company_compliance_roc_llp_status,name='update_company_compliance_roc_llp_status'),
  path('employee/backoffice/authorized-paidup-capital-increase/<int:record_id>/update-status/',views.update_authorized_paidup_capital_increase_status,name='update_authorized_paidup_capital_increase_status'),
  path('employee/backoffice/din-kyc/<int:record_id>/update-status/',views.update_din_kyc_status,name='update_din_kyc_status'),
  path('employee/backoffice/ngo-darpan/<int:record_id>/update-status/',views.update_ngo_darpan_status,name='update_ngo_darpan_status'),
  path('employee/backoffice/itr-filing/<int:record_id>/update-status/',views.update_itr_filing_status,name='update_itr_filing_status'),
  path('employee/backoffice/inc-20a/<int:record_id>/update-status/',views.update_inc_20a_status,name='update_inc_20a_status'),
  path('employee/backoffice/gem-registration/<int:record_id>/update-status/',views.update_gem_registration_status,name='update_gem_registration_status'),
  path('employee/backoffice/startup-india-seed-funding/<int:record_id>/update-status/',views.update_startup_india_seed_funding_status,name='update_startup_india_seed_funding_status'),
  path('employee/backoffice/csr-1-ngo/<int:record_id>/update-status/',views.update_csr_1_ngo_status,name='update_csr_1_ngo_status'),
  path('employee/backoffice/12a-80g-registration/<int:record_id>/update-status/',views.update_12a_80g_registration_status,name='update_12a_80g_registration_status'),
  path('employee/backoffice/partnership-registration/<int:record_id>/update-status/',views.update_partnership_registration_status,name='update_partnership_registration_status'),
  path('employee/backoffice/get-lead-details/',views.get_lead_details,name='get_lead_details'),
  path('employee/in-out/',views.employee_in_out,name='employee_in_out'),
  path('employee/attendance/check-in/',views.employee_attendance_check_in,name='employee_attendance_check_in'),
  path('employee/attendance/check-out/',views.employee_attendance_check_out,name='employee_attendance_check_out'),
  path('employee/attendance/records/',views.employee_attendance_records,name='employee_attendance_records'),
  path('employee/settings/',views.employee_settings,name='employee_settings'),
  path('employee/leave/',views.employee_leave,name='employee_leave'),
  path('employee/leave/apply/',views.employee_leave_apply,name='employee_leave_apply'),
  path('employee/leave/<int:leave_id>/view/',views.employee_leave_view,name='employee_leave_view'),
  path('employee/leave/<int:leave_id>/cancel/',views.employee_leave_cancel,name='employee_leave_cancel'),
  path('employee/leads/',views.employee_leads,name='employee_leads'),
  path('employee/quotes/',views.employee_quotes,name='employee_quotes'),
  path('employee/quotes/<int:quote_id>/view/',views.employee_quote_view,name='employee_quote_view'),
  path('employee/quotes/<int:quote_id>/delete/',views.employee_quote_delete,name='employee_quote_delete'),
  path('employee/quotes/onboard/<int:onboard_id>/view/',views.employee_onboard_view,name='employee_onboard_view'),
  path('employee/quotes/onboard/<int:onboard_id>/delete/',views.employee_onboard_delete,name='employee_onboard_delete'),
  path('employee/clients/',views.employee_clients,name='employee_clients'),
  path('employee/invoices/',views.employee_invoices,name='employee_invoices'),
  
  # Personal Section URLs
  path('employee/profile/',views.employee_profile,name='employee_profile'),
  path('employee/documents/',views.employee_documents,name='employee_documents'),
  path('employee/documents/upload/',views.employee_documents_upload,name='employee_documents_upload'),
  path('employee/documents/<int:doc_id>/delete/',views.employee_documents_delete,name='employee_documents_delete'),
  path('employee/payroll/',views.employee_payroll,name='employee_payroll'),
  path('employee/achievements/',views.employee_achievements,name='employee_achievements'),
  path('employee/messages/',views.employee_messages,name='employee_messages'),
  path('employee/messages/send/',views.employee_send_message,name='employee_send_message'),
  path('employee/messages/get/',views.employee_get_messages,name='employee_get_messages'),
  
  path('leads/<int:lead_id>/assign_engineer/', views.assign_engineer, name='assign_engineer'),
  path('leads/assign-to-employee/', views.assign_lead_to_employee, name='assign_lead_to_employee'),
  path('leads/bulk-assign/', views.bulk_assign_leads, name='bulk_assign_leads'),
  path('leads/update-status/', views.update_lead_status, name='update_lead_status'),
  path('leads/update-notes/', views.update_lead_notes, name='update_lead_notes'),

  


  # // this is for footer urls 

]

